Citizen.CreateThread(function()
  -- NAMES WHEELS
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_06"),"Benz 06")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_07"),"Benz 07")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_08"),"Benz 08")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_09"),"Benz 09")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_10"),"Benz 10")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_11"),"Benz 11")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_12"),"Benz 12")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_13"),"Benz 13")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_14"),"Benz 14")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_15"),"Benz 15")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_16"),"Benz 16")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_17"),"Benz 17")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_18"),"Benz 18")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_19"),"Benz 19")
	AddTextEntryByHash(GetHashKey("wheel_drft_benz_10"),"Benz 20")
  
end)
